### ISSUE TITLE
display image over internet

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/nativehtml#10]
how can i use this library when i have some images over internet not assets? i get error and its must be use background, is any solution?

**Comment by stefanhaustein** [comment]
Images on the internet should just work like asset images. What error did you observe? Did you set the base URL? Can you provide a sample HTML snippet that doesn't work as expected?

**Comment by pishguy** [comment]
@stefanhaustein  yes, sure

```
   try {
       String text   = "<p><img src='https://images.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'></p>";
       Reader reader = new StringReader(text);
       myHiClass htmlView = new myHiClass(this);
       htmlProcessor.parse(reader, htmlView);
       ScrollView scrollView = new ScrollView(this);
       scrollView.addView(htmlView);
       setContentView(scrollView);
       makeSelectable(scrollView);
   } catch (Exception e) {
       e.printStackTrace();
       Log.e("HtmlView ", e.getMessage());
       throw new RuntimeException(e);
   }
```


screen shot:

http://rupload.ir/upload/xhkjmp6q7kq3x812fvu2.png

**Comment by pishguy** [comment]
@stefanhaustein I'm so sorry, after some delay time image can be show
