### ISSUE TITLE
show image with AspectRatio

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/nativehtml#11]
in my html some images are large, such as width, how can i fit image or using `AspectRatio` for them?

for example:

http://cdn.time.ir/App_Themes/Default-fa-IR/Images/summerHeader.jpg

**Comment by stefanhaustein** [comment]
What did you try? 

    <img src="http://cdn.time.ir/App_Themes/Default-fa-IR/Images/summerHeader.jpg"> 

and setting the width attribute accordingly? Or a background image?

**Comment by pishguy** [comment]
@stefanhaustein its not background image and i would like to set custom size to show correctly on all android device resulation or automatically can use `android:adjustViewBounds`

**Comment by stefanhaustein** [comment]
If you set the desired image as a background image of a div, you should be able to set it to a fixed percentage of the width using css styles
