### ISSUE TITLE
Disable debug output

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#13]
I just saw that using the Android library prints debug output to the Android monitor when parsing the HTML data:

```
I/System.out:   Entering p
I/System.out:   Leaving p
I/System.out:   Entering hr
I/System.out:   Leaving hr
I/System.out:   Entering h3
...
```

After this there seems to be some CSS style output, too. As I do not use any CSS inside my HTML file, this seems to be output of this library.

```
I/System.out: applying stylesheet: hr {display: block;
I/System.out: border-top-color: #888888;
I/System.out: border-top-style: solid;
I/System.out: margin-top: 8px;
I/System.out: margin-bottom: 8px;
I/System.out: /* specifity: -999999 */
I/System.out: }
...
```

Is there a way to disable this debug data output?

**Comment by stefanhaustein** [comment]
Should be fixed now in v1.0.3
