### ISSUE TITLE
Click Event

### ISSUE THREAD

**Issue by drparasmehta** [stefanhaustein/nativehtml#14]
I want to pass on onClickListener event to parent container. 

Just now, when text/table-cell is there, the click event is handled there only, while click on blank area is calling event on parent container.

I do not want selection option in textview. 
How to do that?

**Comment by stefanhaustein** [comment]
I guess the simplest option would be to make text selection optional... Either via some setting or by supporting  user-select.

**Comment by stefanhaustein** [comment]
v1.0.4 has Android support for user-select: none
