### ISSUE TITLE
Broken sublists on Android

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#15]
Displaying sublists on Android seems to be somehow broken when using the correct HTML syntax (before the horizontal rule). Using the wrong syntax (after the horizontal rule), everythings seems to work fine. ([Screenshot](https://user-images.githubusercontent.com/7279752/31046715-ac32b66a-a5fd-11e7-8526-feeb27201528.png))

HTML file:

```html
<html>
<body>

<!-- Correct syntax, but broken -->
<ul>
    <li>List item one</li>
    <li>List item two with subitems:
        <ul>
            <li>Subitem 1</li>
            <li>Subitem 2</li>
        </ul>
    </li>
    <li>Final list item</li>
</ul>

<hr>

<!-- Incorrect syntax, but working -->
<ul>
    <li>List item one</li>
    <li>List item two with subitems:</li>
    <ul>
        <li>Subitem 1</li>
        <li>Subitem 2</li>
    </ul>
    <li>Final list item</li>
</ul>

</body>
</html>
```

Message in Android Monitor:

```
Ignoring </li>: opening tag not found in [html, body, ol] at END_TAG </li>@12:10 in java.io.InputStreamReader@aef40a38
```

When replacing the unorderded lists with ordered ones, the effect is the same. The only difference is that there seems to be a slight vertical shift between the list mark and the text ([Screenshot](https://user-images.githubusercontent.com/7279752/31046739-45490188-a5fe-11e7-9988-809a42c88141.png)).

**Comment by stefanhaustein** [comment]
Thanks! Should be fixed with v1.0.5
