### ISSUE TITLE
Possible adjustLastLine computation error.

### ISSUE THREAD

**Issue by MartB** [stefanhaustein/nativehtml#22]
https://github.com/stefanhaustein/nativehtml/blob/6850845ef21236c697d528a83365252e27ebba3b/shared/src/main/java/org/kobjects/nativehtml/layout/BlockLayout.java#L160

Im not familiar enough with the library yet but the missing break looks like a mistake to me.
Can you confirm ?

**Comment by stefanhaustein** [comment]
Thanks! Should be fixed now at head.
