### ISSUE TITLE
hypertext.html demo not showing sample image

### ISSUE THREAD

**Issue by hurelhuyag** [stefanhaustein/nativehtml#23]

**Comment by stefanhaustein** [comment]
On which platform did you observe this? Is this always reproducible?

**Comment by hurelhuyag** [comment]
build.gradle
android {
    compileSdkVersion 27
    buildToolsVersion '25.0.2'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
}

device: nexus5 stock android 6.0.1

**Comment by stefanhaustein** [comment]
Sorry for the delay -- should be fixed with v1.0.6
