### ISSUE TITLE
Which components are supported?

### ISSUE THREAD

**Issue by nilskretschmer** [stefanhaustein/nativehtml#26]
Hi,
I am interested in this project. I am developing a Notes App and I want to parse HTML to native ViewComponents. 

Which components/tags are supported? Are there checkboxes or Lists?

**Comment by stefanhaustein** [comment]
Lists should work with `<ul><li>` ... or `<ul><ol>`...

For checkboxes, please use `<input type="checkbox">`

**Comment by nilskretschmer** [comment]
Ah nice thanks for the reply. I will give it a try.
I already have HTML which I want to convert to native components. Is there something possible like
`htmlView.loadHtml(String html);` ?

On the other hand I would have to write my html String to a file to render it afterwards. That's a bit tricky. 

In addition it would be very useful to have a complete list of html tags and their native UI component supported by the library.

**Comment by nilskretschmer** [comment]
Using `<input type="checkbox">` works and gives me a CheckBox.
I tried to get this CheckBox from the htmlView but it seems that there is only an `AndroidContainerElement`? How to get the Android CheckBox from the view?

**Comment by FriedrichFroebel** [comment]
For the string loading part, something like the following should be possible (untested):

```java
HtmlView htmlView = new HtmlView(this);

try {
    Reader htmlReader= new StringReader(myStringWithTheHtmlData);
    // Just a dummy as a URI is needed.
    URI htmlUri = new URI("string:///whatever");

    // Load the formatted HTML into the view.
    htmlView.loadHtml(htmlReader, htmlUri);
} catch (IOException | URISyntaxException exception) {
    Toast.makeText(getApplicationContext(), "Error loading HTML.",
        Toast.LENGTH_SHORT).show();
    return;
}

// Make the formatted HTML visible.
ScrollView scrollView = (ScrollView) findViewById(R.id.scrollView);
scrollView.addView(htmlView);
```

**Comment by stefanhaustein** [comment]
AndroidContainerElement is a subclass of ViewGroup. You should be able to find the checkbox by iterating the child views recursively.
