### ISSUE TITLE
SWT support

### ISSUE THREAD

**Issue by charliewolf** [stefanhaustein/nativehtml#3]
Are there any plans to support SWT?

**Comment by stefanhaustein** [comment]
Not really at the moment. Not sure if it is immediately feasible at all, IIRC there might be an issue with SWT widgets requiring the parent in the parent in the constructor. Also, rendering relies on native text block formatting capabilities, not sure if there is an adequate SWT widget for that.

**Comment by stefanhaustein** [comment]
P.S. Also, gradle + SWT = pain. But looked at StyledText -- might actually be feasible.  Do you have a use case?

**Comment by charliewolf** [comment]
@stefanhaustein Yeah, I'd like to use it in an app I'm deveoping.  Can you clarify what you mean by "there might be an issue with SWT widgets requiring the parent in the parent in the constructor."? Not sure if I understand that one.

As far as gradle + SWT, I find this terrifying incantation to work:
```
configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            // The maven property ${osgi.platform} is not handled by Gradle
            // so we replace the dependency, using the osgi platform from the project settings
            substitute module('org.eclipse.platform:org.eclipse.swt.${osgi.platform}') with module("org.eclipse.platform:org.eclipse.swt.$osgi_platform:$swt_version")
        }
    }
}
```
and in `buildscript:
```
    ext {
        if (org.gradle.internal.os.OperatingSystem.current().isLinux()) {
            osgi_platform = 'gtk.linux.x86_64'
        }
        else if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
            osgi_platform = 'win32.win32.x86'
        }
        else if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
            osgi_platform = 'cocoa.macosx.x86_64'
        }
        swt_version = '3.105.3'
    }
```

**Comment by stefanhaustein** [comment]
Do you want to take a stab at SWT support? Perhaps we could find a time where I could be available on chat.

**Comment by charliewolf** [comment]
I don't have time to port this at the moment so closing this. If someone else wants this feel free to reopen.
