### ISSUE TITLE
Use in Gradle via Jitpack

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#4]
I tried to use this library inside the Gradle buildfile of my Android application, but it keeps failing.

Jitpack is included inside the top level build file, but when trying to do a Gradle sync for my application after inserting

    compile 'com.github.stefanhaustein:nativehtml:master-SNAPSHOT'

to the `dependencies` part of the app build file I get the following error:

> Error: Failed to resolve: com.github.stefanhaustein:shared:master-23608c104c-1

Is there a way to fix this?

**Comment by stefanhaustein** [comment]
Sorry for the inconvenience! 
Should be fixed now:

https://jitpack.io/com/github/stefanhaustein/nativehtml/master-b90e5acaa7-1/build.log

The maven plugin was missing in the gradle build files and there was a strange issue with the kxml/xmlpull dependency.

Can you double-check whether the gradle dependency provided in the readme works as intended? O:)

**Comment by FriedrichFroebel** [comment]
The Gradle build could be finished now.
