### ISSUE TITLE
read from string

### ISSUE THREAD

**Issue by pishguy** [stefanhaustein/nativehtml#6]
how can i parse html from String?

**Comment by FriedrichFroebel** [comment]
You could do something like this:

```java
String myString = "<html><body>Hello world.</body></html>";
Reader reader = new StringReader(myString);
URI uri = new URI(...); // Use whatever you like (but valid URI syntax).
HtmlView htmlView = new HtmlView(this);
htmlView.loadHtml(reader, uri);
```

**Comment by pishguy** [comment]
@FriedrichFroebel Thanks to reply, but i dont understand me whats this line and how can i set that:

`URI uri = new URI(...);` whats it for?

**Comment by FriedrichFroebel** [comment]
The [`HtmlView`](https://github.com/stefanhaustein/nativehtml/blob/master/android/src/main/java/org/kobjects/nativehtml/android/HtmlView.java) class provides two `load` methods: One to read from a URL and one to parse a `Reader`. The method to parse the reader requires an additional `baseUrl` parameter (I do not know the purpose of doing this, but if you are interested in the reasons, you may find an answer when diving [into the code](https://github.com/stefanhaustein/nativehtml/blob/master/shared/src/main/java/org/kobjects/nativehtml/io/HtmlParser.java)).

I recommend you the read the corresponding [Javadoc](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) for the URI class.

**Comment by stefanhaustein** [comment]
The baseUri is needed to resolve relative links

**Comment by pishguy** [comment]
@stefanhaustein @FriedrichFroebel i just read library source code, i dont understand why when we have html on string we have to use `uri`, could you tell me simple example to know how can i use that?

**Comment by pishguy** [comment]
@stefanhaustein 

> The baseUri is needed to resolve relative links

then can i pass null, its right

**Comment by pishguy** [comment]
i can't use simply this library, i think htmlview2 is simple than this library, for example:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        htmlView = new HtmlView(this);
        ScrollView scrollView = new ScrollView(this);
        scrollView.addView(htmlView);
        setContentView(scrollView);

        try {
            String   myString = "<html><body><p style='text-color:black;'>Hello world.</p></body></html>";
            Reader   reader   = new StringReader(myString);
            URI      uri      = new URI("http://google.com"); // Use whatever you like (but valid URI syntax).
            HtmlView htmlView = new HtmlView(this);
            htmlView.loadHtml(reader, uri);
        } catch (URISyntaxException e) {
            Log.e("err ", e.getMessage());
            throw new RuntimeException(e);
        }
    }
```
whats `URI` when i try to load html from string? with this sample my phone screen is white and i dont see hello world on that,

is it like with `loadDataWithBaseURL` for webView? for example:

`new URI("file:///android_asset/");`

**Comment by stefanhaustein** [comment]
Yes, it's just the base URL for resolving relative URLs. Asset directory seems like a valid choice, but I didn't want to provide a default to avoid potential security issues if users are not aware of this.

I think the problem with your code is the following line repeated in the try-catch block:

     HtmlView htmlView = new HtmlView(this);

It should be deleted there because it creates a second HtmlView that is not attached to anyting
