### ISSUE TITLE
Line breaks not working

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#8]
When using some HTML like `<html><body><h1>This is<br />my heading</h1></body></html>`, the line break seems to get ignored (output is something like `This ismy heading` in the `h1` style).

**Comment by stefanhaustein** [comment]
Did you see this on Android or Swing?
Do you know if br works as expected outside of h1, or is h1 the only case you tested?

**Comment by FriedrichFroebel** [comment]
I tested it on an Android. Trying to use something like `<html><body>Test<br />Second line</body></html>`  seems to fail, too. Therefore I am going to change the issue name.

**Comment by stefanhaustein** [comment]
Thanks for the report! Should be fixed with v1.0.2
