### ISSUE TITLE
Jitpack build failing for the latest master

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#9]
The Jitpack.io build seems to fail for the `master` branch since this commit: 2feebdb28e. This does seem not apply to the release versions as I can use v1.0.1 without problems. Seems like there is something broken with the demo application:

> A problem occurred configuring project ':demo-android'.

By the way: There are some Gradle warnings inside the build log:

> The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
> The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

**Comment by stefanhaustein** [comment]
Current snapshot seems to build fine (the URL is what master-SNAPSHOT was resolved to):
https://jitpack.io/com/github/stefanhaustein/nativehtml/master-v1.0.2-g7f1c887-1/build.log

Perhaps some kind of transient jitpack issue? Sometimes building for the first time on jitpack seems to take quite a while.

Concerning the warnings: I don't think I use the options causing this directly, perhaps they are coming from a plugin that needs corresponding updates?
